### ISSUE TITLE
你好，请问为什么我修改房间号后却显示我修改后的直播间ID为0

### ISSUE THREAD

**Issue by End-Satan** [EndWo/Bilibili-live#1]
![1](https://user-images.githubusercontent.com/17049937/155854935-e5097902-90f1-4660-bfe0-2305b8315c19.png)
恢复之前的文件就是正常的，为什么吖

**Comment by endwo** [comment]
配置文件用的是用户ID，不是直播房间号ID。参见readme里的介绍

**Comment by filwsx** [comment]
it's a long time no comment
